local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>ha", mark.add_file, { desc = "[h]arpoon [a]dd file." })
vim.keymap.set("n", "<leader>hm", ui.toggle_quick_menu, { desc = "[h]arpoon open [m]enu" })

vim.keymap.set("n", "<leader>h1", function()
	ui.nav_file(1)
end, { desc = "[h]arpoon nav to [1]" })
vim.keymap.set("n", "<leader>h2", function()
	ui.nav_file(2)
end, { desc = "[h]arpoon nav to [2]" })
vim.keymap.set("n", "<leader>h3", function()
	ui.nav_file(3)
end, { desc = "[h]arpoon nav to [3]" })
vim.keymap.set("n", "<leader>h4", function()
	ui.nav_file(4)
end, { desc = "[h]arpoon nav to [4]" })
vim.keymap.set("n", "<leader>h5", function()
	ui.nav_file(5)
end, { desc = "[h]arpoon nav to [5]" })
vim.keymap.set("n", "<leader>h6", function()
	ui.nav_file(6)
end, { desc = "[h]arpoon nav to [6]" })
vim.keymap.set("n", "<leader>h7", function()
	ui.nav_file(7)
end, { desc = "[h]arpoon nav to [7]" })
vim.keymap.set("n", "<leader>h8", function()
	ui.nav_file(8)
end, { desc = "[h]arpoon nav to [8]" })
vim.keymap.set("n", "<leader>h9", function()
	ui.nav_file(9)
end, { desc = "[h]arpoon nav to [9]" })
vim.keymap.set("n", "<leader>h0", function()
	ui.nav_file(0)
end, { desc = "[h]arpoon nav to [0]" })
