require("user.alpha")
require("user.comment")
-- require("user.debug")
require("user.devicons")
require("user.indent_blankline")
require("user.keymap")
require("user.gitsigns")
require("user.neogit")
require("user.lightspeed")
require("user.lightbulb")
require("user.lsp")
require("user.lualine")
-- require("user.harpoon")
require("user.colorscheme")
require("user.nvim_cmp")
require("user.nvim_tree")
require("user.persistence")
require("user.options")
require("user.status")
require("user.telescope")
require("user.tree")
require("user.treesitter")
require("user.undotree")
require("user.whichkey")
require("user.diffview")
