-- Generated by Home Manager.
-- See https://wezfurlong.org/wezterm/
local wezterm = require("wezterm")
wezterm.on("update-status", function(window, pane)
	local meta = pane:get_metadata() or {}
	if meta.is_tardy then
		local secs = meta.since_last_response_ms / 1000.0
		window:set_right_status(string.format("tardy: %5.1fs⏳", secs))
	end
end)
wezterm.on("update-right-status", function(window, _)
	local SOLID_LEFT_ARROW = ""
	local ARROW_FOREGROUND = { Foreground = { Color = "#c6a0f6" } }
	local prefix = ""

	if window:leader_is_active() then
		prefix = " " .. utf8.char(0x1f30a) -- ocean wave
		SOLID_LEFT_ARROW = utf8.char(0xe0b2)
	end

	if window:active_tab():tab_id() ~= 0 then
		ARROW_FOREGROUND = { Foreground = { Color = "#1e2030" } }
	end -- arrow color based on if tab is first pane

	window:set_left_status(wezterm.format({
		{ Background = { Color = "#b7bdf8" } },
		{ Text = prefix },
		ARROW_FOREGROUND,
		{ Text = SOLID_LEFT_ARROW },
	}))
end)
return {
	leader = {
		key = "q",
		mods = "ALT",
		timeout_milliseconds = 2000,
	},
	keys = {
		{
			key = "P",
			mods = "CTRL",
			action = wezterm.action.ActivateCommandPalette,
		},
		-- Pane Management
		{
			mods = "LEADER",
			key = "\\",
			action = wezterm.action.SplitHorizontal({ domain = "CurrentPaneDomain" }),
		},
		{
			mods = "LEADER",
			key = "-",
			action = wezterm.action.SplitVertical({ domain = "CurrentPaneDomain" }),
		},
		-- End pane Management
		-- Pane Sizing
		{
			mods = "LEADER",
			key = "h",
			action = wezterm.action.AdjustPaneSize({ "Left", 5 }),
		},
		{
			mods = "LEADER",
			key = "l",
			action = wezterm.action.AdjustPaneSize({ "Right", 5 }),
		},
		{
			mods = "LEADER",
			key = "j",
			action = wezterm.action.AdjustPaneSize({ "Down", 5 }),
		},
		{
			mods = "LEADER",
			key = "k",
			action = wezterm.action.AdjustPaneSize({ "Up", 5 }),
		},
		-- End pane Sizing
	},
	use_fancy_tab_bar = false,
	font = wezterm.font("VictorMono Nerd Font"),
	automatically_reload_config = true,
	font_size = 14,
	hide_tab_bar_if_only_one_tab = true,
	window_decorations = "NONE",
	window_close_confirmation = "NeverPrompt",
	enable_scroll_bar = false,
	color_scheme = "tokyonight_night",
	window_background_opacity = 0.90,
	tab_bar_at_bottom = false,
	colors = {
		tab_bar = {
			background = "#000000",
			active_tab = {
				bg_color = "#24283b",
				fg_color = "#cdd6f4",
			},
			inactive_tab = {
				fg_color = "#bac2de",
				bg_color = "#414868",
				italic = true,
			},
		},
	},
	command_palette_bg_color = "#1a1b26",
	command_palette_fg_color = "#c0caf5",
	command_palette_rows = 12,
}
