-- nixcats/lua/plugins/codediff.lua
-- VSCode-style diff viewer (esmuellert/codediff.nvim)

local ok, codediff = pcall(require, 'codediff')
if not ok then
  return
end

codediff.setup({
  highlights = {
    line_insert = "DiffAdd",
    line_delete = "DiffDelete",
    char_insert = nil,
    char_delete = nil,
    char_brightness = nil,
  },
  diff = {
    layout = "side-by-side",
    disable_inlay_hints = true,
    max_computation_time_ms = 5000,
    ignore_trim_whitespace = false,
    hide_merge_artifacts = false,
    original_position = "left",
    cycle_next_hunk = true,
    cycle_next_file = true,
    jump_to_first_change = true,
    highlight_priority = 100,
    compute_moves = false,
  },
  explorer = {
    position = "left",
    width = 40,
    height = 15,
    indent_markers = true,
    initial_focus = "explorer",
    view_mode = "tree",
    flatten_dirs = true,
    focus_on_select = false,
    visible_groups = {
      staged = true,
      unstaged = true,
      conflicts = true,
    },
  },
  history = {
    position = "bottom",
    width = 40,
    height = 15,
    initial_focus = "history",
    view_mode = "tree",
  },
  keymaps = {
    view = {
      quit = "q",
      toggle_explorer = "<leader>b",
      focus_explorer = "<leader>e",
      next_hunk = "]c",
      prev_hunk = "[c",
      next_file = "]f",
      prev_file = "[f",
      diff_get = "do",
      diff_put = "dp",
      open_in_prev_tab = "gf",
      close_on_open_in_prev_tab = false,
      toggle_stage = "-",
      stage_hunk = "<leader>hs",
      unstage_hunk = "<leader>hu",
      discard_hunk = "<leader>hr",
      hunk_textobject = "ih",
      show_help = "g?",
      align_move = "gm",
      toggle_layout = "t",
    },
    explorer = {
      select = "<CR>",
      hover = "K",
      refresh = "R",
      toggle_view_mode = "i",
      stage_all = "S",
      unstage_all = "U",
      restore = "X",
      toggle_changes = "gu",
      toggle_staged = "gs",
      fold_open = "zo",
      fold_open_recursive = "zO",
      fold_close = "zc",
      fold_close_recursive = "zC",
      fold_toggle = "za",
      fold_toggle_recursive = "zA",
      fold_open_all = "zR",
      fold_close_all = "zM",
    },
    history = {
      select = "<CR>",
      toggle_view_mode = "i",
      refresh = "R",
      fold_open = "zo",
      fold_open_recursive = "zO",
      fold_close = "zc",
      fold_close_recursive = "zC",
      fold_toggle = "za",
      fold_toggle_recursive = "zA",
      fold_open_all = "zR",
      fold_close_all = "zM",
    },
  },
})
