#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m config window_topmost on

yabai -m config external_bar all:24:0

yabai -m config layout bsp
yabai -m config top_padding    10
yabai -m config bottom_padding 48
yabai -m config left_padding   25
yabai -m config right_padding  25
yabai -m config window_gap     25
yabai -m config window_gap 25

yabai -m config mouse_follows_focus        on
yabai -m config focus_follows_mouse        autoraise
yabai -m config window_border_width        8

yabai -m config window_opacity             on
yabai -m config window_opacity_duration    0.25
yabai -m config active_window_opacity      1.0
yabai -m config normal_window_opacity      0.875
yabai -m config window_border_blur off
yabai -m config window_shadow              on

yabai -m config window_placement second_child
yabai -m config split_ratio                0.50
yabai -m config auto_balance               off

# mouse stuff
yabai -m config mouse_modifier             ctrl
yabai -m config mouse_action1              resize
yabai -m config mouse_action2              move

# window border
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xFF6faec0
yabai -m config normal_window_border_color 0xFF3e4050
yabai -m config insert_feedback_color        0xffd75f5f

# don't tile unresizable apps
yabai -m rule --add app="^(Calculator|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility)$" manage=off
yabai -m rule --add app="^(iTerm2)$" manage=off layer=above border=off opacity=1.0 grid=25:25:0:0:0:0

# label spaces
yabai -m space 1 --label Web
yabai -m space 2 --label Dev
yabai -m space 3 --label OpsCenter
yabai -m space 4
yabai -m space 5
yabai -m space 6
yabai -m space 7
yabai -m space 8 --label CommCenter
yabai -m space 9
yabai -m space 0 --label Media

# Enable animations
yabai -m config window_animation_duration 0

# notify sketchybar when window focus is changed
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_title_changed action="sketchybar --trigger title_change"
# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# notify when the yabai config finished loading
sudo yabai --load-sa
echo "yabai configuration loaded.."
